### ISSUE TITLE
Unsupported Element type "camera"

### ISSUE THREAD

**Issue by sromberg** [dbadrian/fastply#1]
Thanks for your approach on reading ply files efficiently! 

Unfortunately, I get the following error when reading a ply file with the header below:

`unknown file: Failure
C++ exception with description "Unsupported Element type camera" thrown in the test body.
`

It seems that the "camera" element is not supported yet. Would be great if you added support. ;-)

```
ply
format binary_little_endian 1.0
comment Generated by NavVis GmbH   
element vertex 7016460
property float x
property float y
property float z
property uchar red
property uchar green
property uchar blue
property float nx
property float ny
property float nz
property float curvature
element camera 1
property float view_px
property float view_py
property float view_pz
property float x_axisx
property float x_axisy
property float x_axisz
property float y_axisx
property float y_axisy
property float y_axisz
property float z_axisx
property float z_axisy
property float z_axisz
property float focal
property float scalex
property float scaley
property float centerx
property float centery
property int viewportx
property int viewporty
property float k1
property float k2
end_header
```

**Comment by dbadrian** [comment]
Thank you for raising this issue. Indeed the current version (master) is pretty hardcoded and serves as a proof-of-concept.  It only supports vertex and face (and the latter one not correctly, as the list property is not parsed correctly yet).

I will soon push a new version to develop, which allows to read an arbitrary number of elements with an arbitrary number of properties, including "list" types.

**Comment by dbadrian** [comment]
See https://github.com/dbadrian/fastply/commit/b0456f65ca2dde1e94fe2994c85dbdc85a247e22 for an update, which is capable of handling your request. However, it is still undergoing larger changes, thus feel free to test, but expect API breaking commits soon.

You can now create a FastPly instance with 0..N (where N is implicitly limited to 256 by the maximum recursion depth - untested) element specifications. Basic edge cases are handled (see unit tests), but it is not fully tested yet for sure. There will be bugs.

Please note that some limitations apply:
  - the list property only supports entries of fixed length (for now?)
  - binary and little endian only
  - Unix only (tested on linux, mac os x should work? untested)
  - C++17 (although it might compile with C++14 and minor warnings)

For your specific use case the following structs should be suitable
```c++
#include <cstdint>

struct __attribute__ ((packed)) VertexLayout {
    float x;
    float y;
    float z;
    uint8_t red;
    uint8_t green;
    uint8_t blue;
    float nx;
    float ny;
    float nz;
    float curvature;
};

struct __attribute__ ((packed)) CameraLayout {
    float view_px;
    float view_py;
    float view_pz;
    float x_axisx;
    float x_axisy;
    float x_axisz;
    float y_axisx;
    float y_axisy;
    float y_axisz;
    float z_axisx;
    float z_axisy;
    float z_axisz;
    float focal;
    float scalex;
    float scaley;
    float centerx;
    float centery;
    int32_t viewportx;
    int32_t viewporty;
    float k1;
    float k2;
};
```
Since there is currently not an updated example file, see unit tests for usage. Please let me know if there are any issues
